### ISSUE TITLE
Question about tooling

### ISSUE THREAD

**Issue by tanskann** [ahmetb/kubernetes-networkpolicy-tutorial#2]
Hi

What tool is used to draw https://github.com/ahmetb/kubernetes-networkpolicy-tutorial/blob/master/img/8.gif ? :)

Br

Niklas

**Comment by ahmetb** [comment]
Google Slides + GIFmaker.me

**Comment by aaranmcguire** [comment]
Sorry to ask a noob question, but I really like how you've made them gifs and want to replicate them with my own labels. So... How did you get the lines to animate? Manually?! Would it be possible to share the Google slides?

**Comment by stvnwrgs** [comment]
@aaranmcguire https://blog.tcea.org/tag/gifmaker-me/
