### ISSUE TITLE
Deny policy not taking effect

### ISSUE THREAD

**Issue by prys** [ahmetb/kubernetes-networkpolicy-tutorial#3]
I'm following this tutorial on a AWS hosted Kubernetes cluster (v1.7.2), built using kops (v1.7.0)  but the deny policy doesn't block traffic. I've tried this with various network plug-ins (i.e. weave / calico / canal etc) but the result is the same.

**Comment by jianchen2580** [comment]
+1 not working

**Comment by ahmetb** [comment]
@prys it's likely that your Network Plugin setup is not working correctly. I'm not familiar with AWS enough to troubleshoot.

**Comment by prys** [comment]
Hi @ahmetb, thanks for replying and apologies for the delay. It turns out that Kops is using manifests that pull down older versions of CNI plugins that don't yet support the new k8s 1.7 network policy semantics - i.e. they need default deny type policy expressed through annotation. Kops 1.8 (alpha) has been updated to pull down later versions of Calico for example, and the behaviour now matches your (excellent) article.
