### ISSUE TITLE
issue with new network policy using IP address

### ISSUE THREAD

**Issue by naveeng68** [ahmetb/kubernetes-networkpolicy-tutorial#7]
I used your 4th example(DENY all traffic from other namespaces)
I created 2 namespace (test1 and test2) and deploy one test services on first namespace,

kubectl run -ti --rm --namespace=test1 --image ubuntu bash -- bash
apt-get update
apt-get --assume-yes install httpie
http http://test-service
and observed it to respond with a 200, indicating that it could connect. This is a good baseline.

now create 2nd namespace test2 and and test it
kubectl run -ti --namespace=test2 --rm --image ubuntu bash -- bash
apt-get update
apt-get --assume-yes install httpie
http http://test-service
and observed a connection error. This is good as it shows that the service discovery didn't work between the new namespaces.

But then tested the IP directly:
http http://100.69.170.122
and it worked. Not good. It's my understanding that the network policy should prevent connections from pods in different namespaces.

how can we overcome above issue?

**Comment by ahmetb** [comment]
@naveeng68 when you're on different namespaces you can't just query `http://test-service`. It will resolve to the `test-service` in the current namespace.

Try `http://test-service.test1` from test2 namespace and try `http://test-service.test2` from test1 namespace. This should solve your problem. (If it does, please close this issue.)

**Comment by naveeng68** [comment]
Yes a service name will only work within a namespace and what is currently setup blocks this from other namespaces. But the problem is that when I lookup the clusterIP and then try from a pod in a different namespace, it works. This shouldn't be allowed. please check above example. hostname is fine but by IP address has resolved (it should not),

**Comment by ahmetb** [comment]
@naveeng68 I just tried this and it enforces the cross-namespasce policy just fine for both hostname and IP address.

I think your cluster might not have network policy enabled. (When there's no networking plugin enabled to enforce the policy, the policy will be silently ignored.)

**Comment by naveeng68** [comment]
could you please let me know how we enable network policy in cluster, If it is not enable then. how its working with host(I am getting issue flu with IP address)

**Comment by ahmetb** [comment]
https://github.com/ahmetb/kubernetes-networkpolicy-tutorial/blob/master/00-create-cluster.md

**Comment by naveeng68** [comment]
I am using AWS, So please let me know how to enable network policy in cluster AWS.
